services:
    BD\PlatformQueryFieldType\FieldType\Query\Type:
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: query}

    BD\PlatformQueryFieldType\FieldType\Mapper\QueryFormMapper:
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: query }
            - { name: ez.fieldFormMapper.value, fieldType: query }
